from fastapi import APIRouter

from app.api.v1 import auth, blog, enrollments, geo, payments, pedagogy, profile, public, scheduling, users

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(profile.router)
api_router.include_router(profile.candidat_router)
api_router.include_router(users.admin_router)
api_router.include_router(users.gerant_router)
api_router.include_router(public.router)
api_router.include_router(geo.router)
api_router.include_router(enrollments.gerant_router)
api_router.include_router(enrollments.candidat_router)
api_router.include_router(enrollments.moniteur_router)
api_router.include_router(scheduling.moniteur_router)
api_router.include_router(scheduling.gerant_sched_router)
api_router.include_router(scheduling.notifications_router)
api_router.include_router(payments.router)
api_router.include_router(payments.admin_router)
api_router.include_router(blog.public_router)
api_router.include_router(blog.admin_router)
api_router.include_router(pedagogy.admin_router)
api_router.include_router(pedagogy.candidat_router)
